config/routes.rb
Rails.application.routes.draw do
  get 'fire/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show] do
    resources :reports, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def create
    puts 'Creating report'
    puts 'Fetching user information...'
    sleep(10)
    puts 'Building PDF...'
    sleep(10)
    puts 'Uploading PDF to S3...'
    sleep(10)
    puts 'Report created'

    flash.alert = 'Report created'
    redirect_to request.referer
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReportApplication</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <div class="alert alert-info">
        <%= msg %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>Users list</h1>

<% @users.each do |user| %>
  <p><%= link_to "#{user.name} #{user.last_name}", user_path(user.id) %></p>
<% end %>

app/views/users/show.html.erb
<div>
  <h1>User Details</h1>
  <p>
    Name: <%= @user.name%><br>
    Last name: <%= @user.last_name%><br>
    Age: <%= @user.age%><br>
    Nationality: <%= @user.nationality%>
  </p>
  
  <%= link_to '<button type="button">Create Report</button>'.html_safe, user_reports_path(@user.id), method: :post %>
</div>